name: Messaging

on:
 push:
    branches: [ master ]
    paths: 
      - '**'

 pull_request:
    branches: [ master ]
    paths: 
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x
   
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Pack Milvasoft.Caching.InMemory project
      run: dotnet pack --no-build --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg -o .
    
    - name: Publish package to NuGet
      run: dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
